defaults: &defaults
  fog_provider: 'AWS'
  aws_access_key_id: "<%= ENV['1D8S6N5SRNV1J2S0M3R2'] %>"
  aws_secret_access_key: "<%= ENV['VnEiLgWaeWdaq/2gkOwUScHMriBRR0DUYmg9ZPQa''] %>"
  # To use AWS reduced redundancy storage.
  # aws_reduced_redundancy: true
  fog_directory: "staticimages"
  # You may need to specify what region your storage bucket is in
  # fog_region: "eu-west-1"
  existing_remote_files: keep
  # To delete existing remote files.
  # existing_remote_files: delete
  # Automatically replace files with their equivalent gzip compressed version
  # gzip_compression: true
  # Fail silently.  Useful for environments such as Heroku
  # fail_silently: true

development:
  <<: *defaults
  enabled: false

test:
  <<: *defaults
  enabled: false

staging:
  <<: *defaults
  fog_directory: "staticimages"

production:
  <<: *defaults
